sudo: required

services:
    - docker

script:
    - docker-compose pull
    - docker-compose up -d
    - docker ps
script:
#    - while ! curl --retry 10 --retry-delay 5 -v http://lb >/dev/null; do sleep 1; done
#    - docker-compose scale web=5
