sudo: required

services:
    - docker

language: bash

before_script:
    - docker-compose pull
    - docker-compose up -d
    - docker-compose scale web=5

script:
    - curl --retry 10 --retry-delay 5 -v http://0.0.0.0
    - curl --retry 10 --retry-delay 5 -v http://0.0.0.0    
