web:
  build: .
  volumes:
   - .:/code
  links:
   - redis
  expose:
   - "5000"
  environment:
   - VIRTUAL_HOST=0.0.0.0
redis:
  image: redis
lb:
  image: jwilder/nginx-proxy
  links:
   - web
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
   - "80:80"
